# Generated by Django 5.0.1 on 2024-01-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moderador',
            fields=[
                ('idmoderador', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=41)),
                ('fechanacimiento', models.DateField(db_column='fechaNacimiento')),
                ('nacionalidad', models.CharField(max_length=20)),
                ('domicilio', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40)),
                ('observaciones', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'moderador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('idpost', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=110)),
                ('contenido', models.CharField(max_length=5000)),
                ('fecha', models.DateField()),
                ('autor', models.CharField(max_length=80)),
                ('extracto', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'post',
                'managed': True,
            },
        ),
    ]
