# Generated by Django 5.0.1 on 2024-01-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderadores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moderador',
            new_name='Moderadore',
        ),
        migrations.AlterModelTable(
            name='moderadore',
            table='moderadore',
        ),
    ]
