# Generated by Django 5.0.1 on 2024-01-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderadores', '0003_alter_post_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idpost',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
